# Generated by Django 5.0.4 on 2024-06-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authname', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('download', models.IntegerField(default=0)),
                ('actual_price', models.FloatField(default=0)),
                ('on_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('authname', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('pdffile', models.FileField(blank=True, null=True, upload_to='')),
                ('read', models.IntegerField(default=0)),
                ('download', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('authname', models.CharField(max_length=255)),
                ('voice', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('spotify_link', models.CharField(max_length=300, null=True)),
                ('youtube_link', models.CharField(max_length=300, null=True)),
                ('listener', models.IntegerField(default=0)),
            ],
        ),
    ]
