# Generated by Django 5.0.3 on 2024-07-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_webcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
